server {
    listen 80;
    server_name localhost;

    root /srv/www/static;
    index index.html;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Node.js Express
    location /node/ {
        rewrite ^/node/(.*)$ /$1 break;
        proxy_pass http://node-express:3000 ;
    }

    # Python Django
    location /python/ {
        rewrite ^/python/(.*)$ /$1 break;
        proxy_pass http://python-django:8000;
    }

    # PHP Laravel
    location /php/ {
        rewrite ^/php/(.*)$ /$1 break;
        proxy_pass http://php-laravel:80;
    }
}